- apt: name=nginx
- service: name=nginx enabled=yes
# - copy: src=htpasswd dest=/etc/nginx/htpasswd
- template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: reload nginx
