- shell:
    cmd: curl https://deb.nodesource.com/gpgkey/nodesource.gpg.key | /usr/bin/gpg --dearmor > /usr/share/keyrings/nodesource.gpg
    creates: /usr/share/keyrings/nodesource.gpg
- apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/{{node_version}} {{ansible_distribution_release}} main
    filename: nodesource
- apt: name=nodejs
- npm: name=pnpm global=true
